import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ReactLenis } from "@/components/smooth-scroll";
import { ThemeProvider } from "@/components/theme-provider";
import { Navbar } from "@/components/navbar";

const satoshi = localFont({
	src: "./fonts/Satoshi-Variable.woff2",
	variable: "--font-satoshi",
});
const tanker = localFont({
	src: "./fonts/Tanker-Regular.woff2",
	variable: "--font-tanker",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${satoshi.variable} ${tanker.variable} antialiased`}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<ReactLenis root>{children}</ReactLenis>
				</ThemeProvider>
				<Navbar />
			</body>
		</html>
	);
}
